using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace UnknownSite0.Plugins.SourceGenerators
{
    [Generator(LanguageNames.CSharp)]
    public class PluginGenerator : IIncrementalGenerator
    {
        private const string PluginBaseType = "UnknownSite0.Plugins.Loader.Plugins.Plugin";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var candidates = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax cds
                        && cds.BaseList != null
                        && !cds.Modifiers.Any(SyntaxKind.AbstractKeyword),
                    transform: static (ctx, ct) => Analyze(ctx, ct))
                .Where(static c => c is not null);

            context.RegisterSourceOutput(candidates.Collect(), static (spc, list) => Emit(spc, list));
        }

        private static PluginCandidate? Analyze(GeneratorSyntaxContext context, CancellationToken ct)
        {
            var classDecl = (ClassDeclarationSyntax)context.Node;
            if (context.SemanticModel.GetDeclaredSymbol(classDecl, ct) is not INamedTypeSymbol symbol)
                return null;

            // 检查继承链中是否包含 Plugin
            bool inheritsPlugin = false;
            for (var t = symbol.BaseType; t != null; t = t.BaseType)
            {
                if (t.ToDisplayString() == PluginBaseType) { inheritsPlugin = true; break; }
            }
            if (!inheritsPlugin) return null;

            bool isPartial = classDecl.Modifiers.Any(SyntaxKind.PartialKeyword);
            bool hasOnInit = symbol.GetMembers("OnInit")
                .OfType<IMethodSymbol>()
                .Any(m => m.IsStatic && m.Parameters.Length == 1);
            bool hasModuleInit = symbol.GetMembers()
                .OfType<IMethodSymbol>()
                .Any(m => m.GetAttributes().Any(a =>
                    a.AttributeClass?.ToDisplayString() == "System.Runtime.CompilerServices.ModuleInitializerAttribute"));

            string ns = symbol.ContainingNamespace.IsGlobalNamespace
                ? string.Empty
                : symbol.ContainingNamespace.ToDisplayString();

            return new PluginCandidate(
                symbol.Name,
                ns,
                isPartial,
                hasOnInit,
                hasModuleInit,
                symbol.Locations[0]);
        }

        private static void Emit(SourceProductionContext ctx, ImmutableArray<PluginCandidate?> candidates)
        {
            foreach (var c in candidates)
            {
                if (c is null) continue;
                var p = c.Value;

                if (!p.IsPartial)
                {
                    ctx.ReportDiagnostic(Diagnostic.Create(new DiagnosticDescriptor(
                        "PLG001",
                        "Plugin 类必须声明为 partial",
                        $"插件类 '{p.ClassName}' 需要声明为 partial 才能生成引导代码",
                        "SourceGenerator",
                        DiagnosticSeverity.Error,
                        isEnabledByDefault: true), p.Location));
                    continue;
                }

                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("#pragma warning disable CA2255");
                sb.AppendLine("#nullable enable");
                sb.AppendLine("using System;");
                sb.AppendLine("using System.Runtime.CompilerServices;");
                sb.AppendLine("using System.Runtime.InteropServices;");
                sb.AppendLine("using UnknownSite0.Plugins.Loader.Plugins;");
                sb.AppendLine();

                if (!string.IsNullOrEmpty(p.Namespace))
                {
                    sb.AppendLine($"namespace {p.Namespace}");
                    sb.AppendLine("{");
                }

                string indent = string.IsNullOrEmpty(p.Namespace) ? "" : "    ";
                sb.AppendLine($"{indent}partial class {p.ClassName}");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    private static {p.ClassName}? __generatedInstance;");
                sb.AppendLine();

                // ModuleInitializer 自动注册 PluginInfo
                if (!p.HasModuleInit)
                {
                    sb.AppendLine($"{indent}    [ModuleInitializer]");
                    sb.AppendLine($"{indent}    internal static void __GeneratedModuleInit()");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        SetPluginInfo(new {p.ClassName}());");
                    sb.AppendLine($"{indent}    }}");
                    sb.AppendLine();
                }

                // OnInit 入口
                if (!p.HasOnInit)
                {
                    sb.AppendLine($"{indent}    [UnmanagedCallersOnly(EntryPoint = \"OnInit\")]");
                    sb.AppendLine($"{indent}    public static void __GeneratedOnInit(IntPtr hostApiTablePtr)");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        __generatedInstance = new {p.ClassName}();");
                    sb.AppendLine($"{indent}        Initialize(hostApiTablePtr, __generatedInstance);");
                    sb.AppendLine($"{indent}    }}");
                    sb.AppendLine();
                }

                //
                sb.AppendLine($"{indent}    [UnmanagedCallersOnly(EntryPoint = \"OnStop\")]");
                sb.AppendLine($"{indent}    public static void __GeneratedOnStop()");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        try");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            __generatedInstance?.OnStop();");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}        finally");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            __generatedInstance = null;");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}    }}");
                sb.AppendLine();

                sb.AppendLine($"{indent}}}");
                if (!string.IsNullOrEmpty(p.Namespace)) sb.AppendLine("}");

                ctx.AddSource($"{p.ClassName}.g.cs", sb.ToString());
            }
        }

        private readonly record struct PluginCandidate(
            string ClassName,
            string Namespace,
            bool IsPartial,
            bool HasOnInit,
            bool HasModuleInit,
            Location Location);
    }
}