// NativePluginKit.SourceGenerators/HostApiGenerator.cs
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace NativePluginKit.SourceGenerators
{
    /// <summary>
    /// 读取 HostApiTable 上标注的 [HostApi] 字段，自动生成对应的插件侧 API 类。
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public class HostApiGenerator : IIncrementalGenerator
    {
        private const string HostApiAttributeName =
            "NativePluginKit.Loader.Constants.HostApiAttribute";

        private const string StringsFreeQualified =
            "NativePluginKit.Features.Strings.Strings.Free";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var fields = context.SyntaxProvider.ForAttributeWithMetadataName(
                HostApiAttributeName,
                predicate: static (node, _) => node is VariableDeclaratorSyntax,
                transform: static (ctx, _) => Extract(ctx))
                .Where(static f => f.HasValue)
                .Select(static (f, _) => f!.Value)
                .Collect();

            context.RegisterSourceOutput(fields, static (spc, list) => Emit(spc, list));
        }

        private static ApiField? Extract(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not IFieldSymbol field)
                return null;

            if (ctx.Attributes.Length == 0)
                return null;

            var attr = ctx.Attributes[0];
            if (attr.ConstructorArguments.Length < 4)
                return null;

            string ns = attr.ConstructorArguments[0].Value as string ?? string.Empty;
            string cls = attr.ConstructorArguments[1].Value as string ?? string.Empty;
            string method = attr.ConstructorArguments[2].Value as string ?? string.Empty;
            var nativeType = attr.ConstructorArguments[3].Value as INamedTypeSymbol;
            var publicType = attr.ConstructorArguments.Length > 4
                ? attr.ConstructorArguments[4].Value as INamedTypeSymbol
                : nativeType;

            if (nativeType is null)
                return null;

            return new ApiField(
                field.Name,
                ns,
                cls,
                method,
                nativeType,
                publicType ?? nativeType);
        }

        private static void Emit(SourceProductionContext ctx, ImmutableArray<ApiField> fields)
        {
            var groups = fields.GroupBy(f => (f.Namespace, f.ClassName));

            foreach (var group in groups)
            {
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("#nullable enable");
                sb.AppendLine("using System;");
                sb.AppendLine("using System.Runtime.InteropServices;");
                sb.AppendLine("using NativePluginKit.Loader.Plugins;");
                sb.AppendLine();
                sb.AppendLine($"namespace {group.Key.Namespace}");
                sb.AppendLine("{");
                sb.AppendLine($"    public static unsafe partial class {group.Key.ClassName}");
                sb.AppendLine("    {");

                foreach (var f in group)
                    EmitMethod(sb, f, ctx);

                sb.AppendLine("    }");
                sb.AppendLine("}");

                ctx.AddSource(
                    $"{group.Key.Namespace}.{group.Key.ClassName}.g.cs",
                    sb.ToString());
            }
        }

        private static void EmitMethod(StringBuilder sb, ApiField f, SourceProductionContext ctx)
        {
            var nativeMethod = f.NativeDelegate.DelegateInvokeMethod;
            var publicMethod = f.PublicDelegate.DelegateInvokeMethod;
            if (nativeMethod is null || publicMethod is null)
                return;

            var nativeParams = nativeMethod.Parameters;
            var publicParams = publicMethod.Parameters;

            if (nativeParams.Length != publicParams.Length)
            {
                ctx.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "NPK002",
                        "Signature mismatch",
                        $"Native and public delegates for '{f.MethodName}' must have the same parameter count.",
                        "HostApiGenerator",
                        DiagnosticSeverity.Error,
                        isEnabledByDefault: true),
                    Location.None));
                return;
            }

            var nativeRet = nativeMethod.ReturnType;
            var publicRet = publicMethod.ReturnType;

            bool returnsVoid = publicRet.SpecialType == SpecialType.System_Void;
            bool returnsString = publicRet.SpecialType == SpecialType.System_String;
            bool returnsBool = publicRet.SpecialType == SpecialType.System_Boolean;
            bool nativeRetIntPtr = nativeRet.SpecialType == SpecialType.System_IntPtr;
            bool nativeRetInt = nativeRet.SpecialType == SpecialType.System_Int32;

            // 检测是否为 Logger 方法
            bool isLoggerMethod =
                f.Namespace == "NativePluginKit.Features.Logger" &&
                f.ClassName == "Log";

            // 方法签名
            string retTypeStr = returnsVoid ? "void" : publicRet.ToDisplayString();
            var paramList = string.Join(", ", publicParams.Select(p =>
                $"{p.Type.ToDisplayString()} {p.Name}"));

            sb.AppendLine($"        public static {retTypeStr} {f.MethodName}({paramList})");
            sb.AppendLine("        {");
            sb.AppendLine("            var api = PluginContext.CurrentApi;");

            // 参数编组：IntPtr ← string
            var tmpVars = new List<string>();
            for (int i = 0; i < publicParams.Length; i++)
            {
                var pub = publicParams[i];
                var nat = nativeParams[i];

                if (nat.Type.SpecialType == SpecialType.System_IntPtr &&
                    pub.Type.SpecialType == SpecialType.System_String)
                {
                    string tmp = $"__p{i}";
                    tmpVars.Add(tmp);

                    if (isLoggerMethod)
                    {
                        // Logger 方法自动加 [PluginName] 前缀
                        sb.AppendLine($"            string __prefixed{i} = \"[\" + PluginContext.PluginName + \"] \" + {pub.Name};");
                        sb.AppendLine($"            IntPtr {tmp} = Marshal.StringToCoTaskMemUTF8(__prefixed{i});");
                    }
                    else
                    {
                        sb.AppendLine($"            IntPtr {tmp} = Marshal.StringToCoTaskMemUTF8({pub.Name});");
                    }
                }
            }

            bool needsTryFinally = tmpVars.Count > 0;

            if (needsTryFinally)
            {
                sb.AppendLine("            try");
                sb.AppendLine("            {");
            }

            // 缩进：try 内部多一级
            string indent = needsTryFinally ? "                " : "            ";

            // 调用参数
            var callArgs = new List<string>();
            for (int i = 0; i < publicParams.Length; i++)
            {
                var pub = publicParams[i];
                var nat = nativeParams[i];

                if (nat.Type.SpecialType == SpecialType.System_IntPtr &&
                    pub.Type.SpecialType == SpecialType.System_String)
                    callArgs.Add($"__p{i}");
                else
                    callArgs.Add(pub.Name);
            }

            // 函数指针类型：delegate* unmanaged<TP1, TP2, ..., TRET>
            var fpParts = new List<string>();
            foreach (var p in nativeParams)
                fpParts.Add(p.Type.ToDisplayString());
            fpParts.Add(nativeRet.ToDisplayString());
            string fpType = $"delegate* unmanaged<{string.Join(", ", fpParts)}>";

            sb.AppendLine($"{indent}var fn = ({fpType})api.{f.FieldName};");
            string call = $"fn({string.Join(", ", callArgs)})";

            if (returnsVoid)
            {
                sb.AppendLine($"{indent}{call};");
            }
            else if (returnsString && nativeRetIntPtr)
            {
                sb.AppendLine($"{indent}IntPtr __ret = {call};");
                sb.AppendLine($"{indent}if (__ret == IntPtr.Zero) return string.Empty;");
                sb.AppendLine($"{indent}var __str = Marshal.PtrToStringUTF8(__ret) ?? string.Empty;");
                sb.AppendLine($"{indent}{StringsFreeQualified}(__ret);");
                sb.AppendLine($"{indent}return __str;");
            }
            else if (returnsBool && nativeRetInt)
            {
                sb.AppendLine($"{indent}return {call} != 0;");
            }
            else
            {
                // 返回类型直接兼容（int、double 等），或 public == native
                sb.AppendLine($"{indent}return {call};");
            }

            if (needsTryFinally)
            {
                sb.AppendLine("            }");
                sb.AppendLine("            finally");
                sb.AppendLine("            {");
                foreach (var tmp in tmpVars)
                    sb.AppendLine($"                Marshal.FreeCoTaskMem({tmp});");
                sb.AppendLine("            }");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }
    }
}