<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PublishAot>true</PublishAot>
		<PublishRelease>true</PublishRelease>
		<PublishTrimmed>true</PublishTrimmed>
		<TrimMode>full</TrimMode>
		<InvariantGlobalization>true</InvariantGlobalization>
		<IlcExportUnmanagedEntrypoints>true</IlcExportUnmanagedEntrypoints>
		<IlcOptimizationPreference>Size</IlcOptimizationPreference>
		<NativeLib>Shared</NativeLib>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<ControlFlowGuard>Guard</ControlFlowGuard>
		<IlcGenerateStackTraceData>false</IlcGenerateStackTraceData>
		<IlcGenerateCompleteTypeMetadata>false</IlcGenerateCompleteTypeMetadata>
		<IlcScanReflection>false</IlcScanReflection>
		<IlcDisableReflection>true</IlcDisableReflection>
		<IlcTrimMetadata>true</IlcTrimMetadata>
		<MetadataUpdaterSupport>false</MetadataUpdaterSupport>
		<DebuggerSupport>false</DebuggerSupport>
		<DebugSymbols>false</DebugSymbols>
		<DebugType>none</DebugType>
		<StripSymbols>true</StripSymbols>
		<StackTraceSupport>false</StackTraceSupport>
		<TrimmerRemoveSymbols>true</TrimmerRemoveSymbols>
		<EventSourceSupport>false</EventSourceSupport>
		<MetricsSupport>false</MetricsSupport>
		<UseSystemResourceKeys>true</UseSystemResourceKeys>
		<HotReloadEnabled>false</HotReloadEnabled>
		<HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
		<XmlResolverIsNetworkingEnabledByDefault>false</XmlResolverIsNetworkingEnabledByDefault>
		<EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\NativePluginKit\NativePluginKit.csproj" />
		<ProjectReference Include="..\..\NativePluginKit.SourceGenerators\NativePluginKit.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

	<ItemGroup>
		<UnmanagedEntryPointsAssembly Include="NativePluginKit" />
	</ItemGroup>

</Project>
